### ISSUE TITLE
Visualization doesn't start on local startup on localhost:9999

### ISSUE THREAD

**Issue by dealenx** [Kitware/HPCCloud#635]
Hello,

I can run the visualization on a container  kitware/hpccloud:nginx (:8888). But when i start a local development frontend (:9999), then i can't open the visualization, usually i don't see errors in browser console and  i just wait loading of the visualization in long time, but after  there is only one error after long waiting:
```
index.js:66 WebSocket connection to 'ws://localhost:9999/proxy?sessionId=5e81a76eb69f894b7d835717&path=ws' failed: Connection closed before receiving a handshake response
```
When i reload the page, then i see that simulation is completed:
![image](https://user-images.githubusercontent.com/4071686/77889803-a5c57c80-7298-11ea-90dc-c4c4baaf406e.png)

Thanks in advance!

**Comment by jourdain** [comment]
Probably because in your dev server you didn't provide a ws socket forwarding rule?

**Comment by dealenx** [comment]
i guess i didn't, usually i start kitware/hpccloud-services with default config.

**Comment by jourdain** [comment]
Maybe the issue is somewhere else. Are you sue that you are getting the server notification?

**Comment by dealenx** [comment]
I am not, after long connection with websocker i have errors with `GET http://localhost:9999/api/v1/notification/stream`. Where i can setting server notification?

![image](https://user-images.githubusercontent.com/4071686/77894714-df4db600-729f-11ea-9cb5-155351c905af.png)

**Comment by dealenx** [comment]
I had no idea, so i had reconfigured the container  kitware/hpccloud:nginx:
```
FROM nginx

RUN rm /etc/nginx/conf.d/default.conf
COPY docker/nginx/nginx.girder.conf /etc/nginx/conf.d/girder.conf
```

docker-compose.yml:
```
  ...
  nginx:
    image: kitware/hpccloud:nginx
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    networks:
      - hc
    working_dir: /usr/share/nginx/html
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - '8888:8888'
    depends_on:
      - girder
      - apache
  ...
```
there are  repositories hpccloud and hpccloud  [was merged](https://github.com/dealenx/hpccloud-kemsu/tree/new-workflow)

and i start  a command for compiling: 
```
    ...
    "build:watch": "webpack --progress --watch --mode development",
    ...
```
